// <auto-generated />
using Labb3_API.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb3_API.data.Interest", b =>
                {
                    b.Property<int>("InterestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestID"));

                    b.Property<string>("InterestDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestID");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestID = 100,
                            InterestDescription = "Playing video games",
                            InterestName = "Gaming"
                        },
                        new
                        {
                            InterestID = 101,
                            InterestDescription = "Any type of exercise like running, sports or gym",
                            InterestName = "Exercise"
                        },
                        new
                        {
                            InterestID = 102,
                            InterestDescription = "Reading books",
                            InterestName = "Reading"
                        },
                        new
                        {
                            InterestID = 103,
                            InterestDescription = "Following the different football leauges in Europe",
                            InterestName = "Football"
                        });
                });

            modelBuilder.Entity("Labb3_API.data.Link", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkID"));

                    b.Property<int>("PersonInterestID")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkID");

                    b.HasIndex("PersonInterestID");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkID = 50,
                            PersonInterestID = 1,
                            Url = "www.youtube.com"
                        },
                        new
                        {
                            LinkID = 51,
                            PersonInterestID = 1,
                            Url = "www.transfermarkt.com"
                        },
                        new
                        {
                            LinkID = 52,
                            PersonInterestID = 2,
                            Url = "www.books.com"
                        },
                        new
                        {
                            LinkID = 53,
                            PersonInterestID = 2,
                            Url = "www.running.com"
                        });
                });

            modelBuilder.Entity("Labb3_API.data.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            FirstName = "Noah",
                            LastName = "Testing",
                            PhoneNum = "1234567"
                        },
                        new
                        {
                            PersonID = 2,
                            FirstName = "Simon",
                            LastName = "Zooming",
                            PhoneNum = "1234567"
                        },
                        new
                        {
                            PersonID = 3,
                            FirstName = "Casper",
                            LastName = "Flyson",
                            PhoneNum = "1234567"
                        },
                        new
                        {
                            PersonID = 4,
                            FirstName = "Svante",
                            LastName = "Svensson",
                            PhoneNum = "1234567"
                        });
                });

            modelBuilder.Entity("Labb3_API.data.PersonInterest", b =>
                {
                    b.Property<int>("PersonInterestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonInterestID"));

                    b.Property<int>("InterestID")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("PersonInterestID");

                    b.HasIndex("InterestID");

                    b.HasIndex("PersonID");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonInterestID = 1,
                            InterestID = 100,
                            PersonID = 1
                        },
                        new
                        {
                            PersonInterestID = 2,
                            InterestID = 102,
                            PersonID = 2
                        });
                });

            modelBuilder.Entity("Labb3_API.data.Link", b =>
                {
                    b.HasOne("Labb3_API.data.PersonInterest", "PersonInterest")
                        .WithMany("Links")
                        .HasForeignKey("PersonInterestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("Labb3_API.data.PersonInterest", b =>
                {
                    b.HasOne("Labb3_API.data.Interest", "Interest")
                        .WithMany("PersonInterest")
                        .HasForeignKey("InterestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Labb3_API.data.Person", "Person")
                        .WithMany("PersonInterest")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Labb3_API.data.Interest", b =>
                {
                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("Labb3_API.data.Person", b =>
                {
                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("Labb3_API.data.PersonInterest", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
